### ISSUE TITLE
Sometimes JerseyServlet fails to start because InjectionManagerFactory can't be found

### ISSUE THREAD

**Issue by steinarb** [steinarb/servlet#3]
Sometimes JerseyServlet fails to start because InjectionManagerFactory can't be found.

Example from karaf.log:
```
15:34:33.571 WARN  [features-3-thread-1] unavailable
java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:74)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:74)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:69)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	at no.priv.bang.servlet.jersey.JerseyServlet.init(JerseyServlet.java:87)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder$WrapperServlet.init(ServletHolder.java:1289)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:602)
```

**Comment by steinarb** [comment]
Fixed by commit 99927fdbe8897c561e50a7f9e78a96d211944942
